# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PSDocs for Azure
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Generate documentation from Azure infrastructure as code (IaC) artifacts.
baseurl: "/PSDocs.Azure/" # the subpath of your site, e.g. /blog
url: "https://azure.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repo: "https://github.com/Azure/PSDocs.Azure"
branch: main

permalink: pretty

# Exclude from processing.
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- SUPPORT.md
- SECURITY.md
- ps-docs.yaml
- ps-rule.yaml
- templates/
- .azure-pipelines/
- .vscode/
- src/
- tests/
- .devcontainer/
- docs/concepts/
- docs/commands/
- docs/release.md

# Build settings
# markdown: kramdown
theme: just-the-docs
color_scheme: nil
plugins:
- jekyll-feed
- jekyll-spaceship

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Azure/PSDocs.Azure" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "PSDocs for Azure on GitHub":
    - "https://github.com/Azure/PSDocs.Azure"
