trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'analyze_arm'
  displayName: 'Analyze templates'
  pool:
    vmImage: 'ubuntu-18.04'
  steps:

  # STEP 1: Install PS Docs Module
  - powershell: | 
     Install-Module -Name 'PSDocs.Azure' -Repository PSGallery -force
     Get-AzRuleTemplateLink | Export-AzTemplateRuleData -OutputPath 'out/templates/';
    displayName: 'Export template data'

  # STEP 5: Run analysis against exported data
  - task: ps-rule-assert@0
    displayName: Analyze Azure template files
    inputs:
      inputType: inputPath
      inputPath: 'out/templates/'     # Read objects from JSON files in 'out/templates/'.
      modules: 'PSRule.Rules.Azure'   # Analyze objects using the rules within the PSRule.Rules.Azure PowerShell module.
