trigger:
- main

jobs:
- job: 'analyze_arm'
  displayName: 'Analyze templates'
  pool:
    vmImage: 'windows-2019'
  steps:
  # STEP 1: Generate Markdowns using PSDocs
  - powershell: | 
      Install-Module -Name 'PSDocs.Azure' -Repository PSGallery -force;
       # Scan for Azure template file recursively in the templates/ directory
       Get-AzDocTemplateFile -Path templates/ | ForEach-Object {
       # Generate a standard name of the markdown file. i.e. <name>_<version>.md
         $template = Get-Item -Path $_.TemplateFile;
         $templateName = $template.Directory.Parent.Name;
         $version = $template.Directory.Name;
         $docName = "$($templateName)_$version";
       # Generate markdown
         Invoke-PSDocument -Module PSDocs.Azure -OutputPath out/docs/ -InputObject $template.FullName -InstanceName $docName;
       }
    displayName: 'Export template data'
    
  # STEP 2: Copy files and publish to artefacts
  - task: AzureFileCopy@4
    inputs:
      SourcePath: 'out/docs/*'
      azureSubscription: 'psdocstest'
      Destination: 'AzureBlob'
      storage: 'targetcopydisk112'
      ContainerName: 'ps-docs'

