# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

@{
    Parameters = 'Parameters'
    Definitions = 'User-defined types definitions'
    Snippets = 'Snippets'
    Outputs = 'Outputs'
    DefaultValue = 'Default value'
    AllowedValues = 'Allowed values'
    AdditionalProperties = 'Additional properties'
    PropertyName = 'Property name'
    ParameterName = 'Parameter name'
    Description = 'Description'
    Type = 'Type'
    Definition = 'Definition'
    UnionTypes = 'Union types'
    DiscriminatorDescription = 'Property used to discriminate between types'
    Mapping = 'Mapping'
    Name = 'Name'
    DefaultTitle = 'Azure template'
    ParameterFile = 'Parameter file'
    CommandLine = 'Command line'
    Required = 'Required'
    RequiredYes = 'Yes'
    RequiredNo = 'No'
    MinValue = 'Minimum value'
    MaxValue = 'Maximum value'
    MinLength = 'Minimum length'
    MaxLength = 'Maximum length'
    Nullable = 'Nullable'
}
