- name: Azure Blob Storage Upload
  uses: bacongobbler/azure-blob-storage-upload@v1.1.1
  with:
    # The connection string for the storage account
    connection_string: ${{ secrets.STORAGEACCOUNTSECRET }}
    # The name of the storage account container these assets will be uploaded to
    container_name: ps-docs
    # The name of the directory you want to upload
    source_dir: 'out/docs/*'